.
.

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -10,7 +10,7 @@ ui_print() {
     echo -e "ui_print $1\nui_print" >> $OUTFD;
   fi;
 }
-abort() { ui_print " "; ui_print "$1"; exit 1; }
+abort() { ui_print " "; ui_print "$1"; umount -lf "$esp_part" "$win_part" 2>/dev/null; exit 1; }
 
 # detect Magisk app/booted flashing
 BOOTMODE=false;
@@ -18,7 +18,7 @@ ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;
 $BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;
 
 # /dev/tmp is safe for both booted and recovery installs
-tmp=/dev/tmp/linux-install;
+tmp=/dev/tmp/install;
 rm -rf "$tmp";
 mkdir -p "$tmp";
 
@@ -26,19 +26,22 @@ mkdir -p "$tmp";
 boot_part=/dev/block/bootdevice/by-name/boot;
 part=/dev/block/by-name;
 esp_part=$part/esp;
+win_part=$part/win;
 linux_part=$part/linux;
 cust_part=$part/cust;
-
-ui_print "#############################################";
-ui_print "#             Linux installation            #";
-ui_print "#############################################";
-ui_print " ";
 zext="$tmp/bin/7zzs";
 mke2fs="$tmp/bin/mke2fs";
+mkfs.fat="$tmp/bin/mkfs.fat";
+bcdctl="$tmp/bin/bcdctl";
+BCD="$tmp/esp/EFI/Microsoft/Boot/BCD";
 
 unzip -o "$ZIPFILE" "bin/*" -d "$tmp" || abort "Failed to extract bin";
 chmod -R 0777 "$tmp";
 
+ui_print "---------------------------------------------";
+ui_print "              Linux installation             ";
+ui_print "---------------------------------------------";
+ui_print " ";
 ui_print "Checking linux partition device: $linux_part";
 if [ ! -e "$linux_part" ]; then
   abort "Linux partition device not found: $linux_part";
@@ -57,9 +60,9 @@ $zext e -so "$ZIPFILE" "image/rootfs.img" > "$linux_part" 2> "$tmp/7z.err" || ab
 ui_print " ";
 ui_print "Done flashing rootfs!";
 
-ui_print "#############################################";
-ui_print "#            Boot Configuration             #";
-ui_print "#############################################";
+ui_print "---------------------------------------------";
+ui_print "             Boot Configuration              ";
+ui_print "---------------------------------------------";
 ui_print " ";
 mkdir -p "$tmp/esp";
 
@@ -69,16 +72,26 @@ if mount | grep -q "$esp_part"; then
 fi;
 mount "$esp_part" "$tmp/esp" || abort "Failed to mount ESP partition";
 
-if ls "$tmp/esp/"[eE][fF][iI]/[mM][iI][cC][rR][oO][sS][oO][fF][tT]/Boot/SiPolicy.p7b >/dev/null 2>&1; then
-  abort "Found Secure Boot config, No-SB config is required for dual-boot.";
+ui_print "Verifying present bootloader configration";
+if [ -f $BCD ] && ! $bcdctl --check $BCD 2>/dev/null | grep -q "testsigning";
+then
+  ui_print "Secure Boot configuration detected. Proceeding to disable Secure Boot.";
+  umount -lf "$win_part" 2>/dev/null;
+  mkdir -p "$tmp/win" && mount.ntfs "$win_part" "$tmp/win" || abort "Failed to mount Windows";
+  mkdir -p "$tmp/win/installer/efi";
+  unzip -o "$ZIPFILE" "installer/*" -d "$tmp/win" || abort "Failed to extract installer files";
+  unzip -o "$ZIPFILE" "efi/*" -d "$tmp/win/installer" || abort "Failed to extract installer into Windows";
+  umount -lf "$esp_part" && $mkfs.fat -F32 -s1 "$esp_part" -n ESPNABU 2>/dev/null;
+  dd if="$esp_part" of=/sdcard/esp_backup.img bs=64M || abort "Failed to backup esp image";
+  dd if="$tmp/win/installer/pe.img" of="$esp_part" bs=64M || abort "Failed to dump pe image";
+else
+  ui_print "Un-secure boot configration found";
+  for i in "$tmp"/esp/[eE][fF][iI]/*; do
+    [ -e "$i" ] || continue; case ${i##*/} in [mM][iI][cC][rR][oO][sS][oO][fF][tT]) ;; *) rm -rf -- "$i";; esac
+  done
+  mkdir -p "$tmp/esp/EFI"
+  unzip -o "$ZIPFILE" "efi/*" -d "$tmp/esp" || abort "Failed to extract efi"
 fi;
- 
-for i in "$tmp"/esp/[eE][fF][iI]/*; do
-  [ -e "$i" ] || continue; case ${i##*/} in [mM][iI][cC][rR][oO][sS][oO][fF][tT]) ;; *) rm -rf -- "$i";; esac
-done;
-mkdir -p "$tmp/esp/EFI";
-unzip -o "$ZIPFILE" "efi/*" -d "$tmp/esp" || abort "Failed to extract efi";
-umount -lf "$esp_part" 2>/dev/null;
 
 # If there is separate boot.img need to be flashed
 unzip -o "$ZIPFILE" "image/boot.img" -d "$tmp" 2>/dev/null;
@@ -86,15 +99,17 @@ if [ ! -f "$tmp/image/boot.img" ]; then
   ui_print "No separate boot.img found, skipping...";
 else
   umount -lf "$cust_part" 2>/dev/null;
-  $mke2fs -t ext4 -F "$cust_part" || abort "Failed to format cust partition";
+  "$mke2fs" -t ext4 -F "$cust_part" || abort "Failed to format cust partition";
   dd if="$tmp/image/boot.img" of="$cust_part" || abort "Failed to flash boot.img to cust partition!";
 fi;
+
+umount -lf "$esp_part" "$win_part" 2>/dev/null;
 ui_print " ";
 ui_print "Boot configuration setup completed!";
 
-ui_print "#############################################";
-ui_print "#          DBKP UEFI installation           #";
-ui_print "#############################################";
+ui_print "---------------------------------------------";
+ui_print "           DBKP UEFI installation            ";
+ui_print "---------------------------------------------";
 ui_print " ";
 
 # modified from the TWRP A/B Installer Backend by osm0sis, Dees_Troy and topjohnwu
